name: Unzip Files

on:
  workflow_dispatch:  # run manually

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unzip archive
        run: |
          unzip backend.zip -d extracted_folder
          rm yourfile.zip
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Extracted zip via workflow" || echo "No changes"
          git push
